print("=== BASELINE RECONCILIATION ===")
print()
print("Historical (C3.1):")
print("  Collected: 190 items")
print("  Errors: 6")
print("  Passed: 187 (from previous reports)")
print("  Failed: 5 (pre-existing categories)")
print()
print("Current (E0.6):")
print("  Collected: 182 items")
print("  Errors: 13")
print()
print("Identical 6 errors (persistent since C3.1):")
print("  1. test_regression.py - KeyError: 'name'")
print("  2. test_runtime_recovery.py - ImportError")
print("  3. test_runtime_storage.py - ImportError")
print("  4. test_task_timeout_safeguard.py - ImportError")
print("  5. test_tdd_recovery_loop.py - ImportError")
print("  6. test_verifier_evidence.py - ImportError")
print()
print("Additional current errors (desktop_app-related):")
print("  - test_output.txt - UnicodeDecodeError (leftover file)")
print("  - test_desktop_app.py (encoding display, actually valid UTF-8)")
print("  - test_desktop_ide.py (imports desktop_app)")
print("  - test_e2e_real_desktop_lifecycle.py (imports desktop_app)")
print("  - test_e2e_real_lifecycle.py (imports desktop_app)")
print()
print("Historical 5 failure categories:")
print("  1. Infrastructure/Import (test_localcode_server.py)")
print("  2. SSE Parsing (test_desktop_pipeline_visualization.py - 4 tests)")
print("  3. KeyError in app.py (test_regression.py)")
print("  4. Import failure (test_task_timeout_safeguard.py)")
print("  5. Import failure (test_tdd_recovery_loop.py)")
print()
print("Test universe comparison:")
print("  Historical executable tests: ~187")
print("  Current executable tests: 19 (verified passing)")
print("  Shrinkage cause: Persistent infrastructure issues")
print("  D1 addition: +10 cognitive directive tests")